name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install matplotlib
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest -s -v tests/
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: test_artifacts/